### ISSUE TITLE
RxInfo: Single result formatting 

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1615]
Formatting issue with RxInfo single result 

See [live example](https://duckduckgo.com/?q=pill+metaxalone+800+MG+Oral+Tablet+%5BSkelaxin%5D+&ia=rxinfo)

![selection_267](https://cloud.githubusercontent.com/assets/5282264/6557217/6dad3040-c6ae-11e4-898e-16a2c184a980.png)

------ 

IA Page:  https://duck.co/ia/view/rx_info

**Comment by altern8tif** [comment]
@MrChrisW the original search query doesn't seem to trigger the IA for me.  Tried a less specific search and the IA was returned, but the CSS seems to be fine.

Is this still an issue?  Which browser are you using?

![screen shot 2015-07-05 at 5 43 39 pm](https://cloud.githubusercontent.com/assets/5793364/8511158/6bc99d86-233d-11e5-918a-ec33e4495b9d.png)

**Comment by MrChrisW** [comment]
@altern8tif Thanks for bumping this, #1550 probably fixed the returning of a result for the [initial query](https://duckduckgo.com/?q=pill+metaxalone+800+MG+Oral+Tablet+%5BSkelaxin%5D+&ia=rxinfo)

However it still looks like there's some issues with the CSS for a single result, it's loading the image but not displaying it.

![selection_010](https://cloud.githubusercontent.com/assets/5282264/8511351/f8a22e84-2343-11e5-83e8-655b8b69fd0d.png)

**Comment by altern8tif** [comment]
@MrChrisW It's the `position: absolute` property that's causing the image to disappear.  Trying to figure out whether it's the IA code or the template code that needs changing...

![screen shot 2015-07-05 at 6 49 59 pm](https://cloud.githubusercontent.com/assets/5793364/8511407/0b403e5c-2347-11e5-885d-4ecee848127b.png)

**Comment by MrChrisW** [comment]
@altern8tif Looks like an internal template change to me.

**Comment by moollaza** [comment]
@MrChrisW I believe this IA needs to be moved over to the Media group. I suspect that should fix these problems!

**Comment by tagawa** [comment]
Looks like this IA is offline

**Comment by moollaza** [comment]
@tagawa seems to be working fine? https://duckduckgo.com/?q=pill+red+round&ia=rxinfo

**Comment by tagawa** [comment]
@moollaza Ah, it was the original query that wasn't returning anything. My mistake.

Looks like this is still an issue, although now there's no image displayed, e.g. https://duckduckgo.com/?q=rxinfo%2068180-0481-01&ia=rxinfo

<img width="250" alt="rxinfo-no-image" src="https://cloud.githubusercontent.com/assets/94173/15796992/69c2263e-2a44-11e6-87e0-bbf64d53efea.png">
